Conditional deploy of html (#69)

diff --git a/.github/workflows/blueprint-docs.yaml b/.github/workflows/blueprint-docs.yaml
--- a/.github/workflows/blueprint-docs.yaml
+++ b/.github/workflows/blueprint-docs.yaml
@@ -3,50 +3,67 @@ name: Build and publish blueprint documentation
 on:
   push:
     branches:
-    - dev_refactor
+    - main
   pull_request:
     branches:
-      - dev_refactor
+    - '*'
 
 jobs:
-  blueprint-docs:
+  blueprint-docs-build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
+    - name: create blueprint environment
+      run: |
+        conda env create --name blueprint --file requirements/requirements.yml
+    - name: Create new project
+      run: |
+        # Note: Make sure python_version is consistent with python-version hardcoded above
+        conda run --name blueprint copier --force --vcs-ref=HEAD python_version=3.9 copy . ./docs/example_project
+        ls
+        echo "==================================="
+        ls docs
+        echo "==================================="
+        ls docs/example_project
     - uses: C2SM/sphinx-action@sphinx-latest
       with:
         pre-build-command: 'pip3 install sphinx_mdinclude'
         docs-folder: "docs/"
-    # Great extra actions to compose with:
     # Create an artifact of the html output.
     - uses: actions/upload-artifact@v1
       with:
         name: DocumentationHTML
         path: docs/_build/
-    # Publish built docs to gh-pages branch.
-    # ===============================
-    - name: Commit documentation changes
-      run: |
-        pwd
-        ls docs
-        echo ' '
-        ls docs/_build
-        git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
-        cp -r docs/_build/html/* gh-pages/
-        cd gh-pages
-        touch .nojekyll
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
-    - name: Push changes
-      # this commit SHA corresponds to tag `v0.6.0`
-      uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
-      with:
-        force: true
-        branch: gh-pages
-        directory: gh-pages
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-    # ===============================
+  blueprint-docs-build-and-deploy:
+    runs-on: ubuntu-latest
+    needs: blueprint-docs-build
+    if: github.ref == 'refs/heads/main'
+    steps:
+      - uses: actions/download-artifact@v1
+        with:
+          name: DocumentationHTML
+          path: docs/_build/
+      # Publish built docs to gh-pages branch.
+      # ===============================
+      - name: Commit documentation changes
+        run: |
+          pwd
+          git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
+          cp -r docs/_build/html/* gh-pages/
+          cd gh-pages
+          touch .nojekyll
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # that.
+      - name: Push changes
+        # this commit SHA corresponds to tag `v0.6.0`
+        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
+        with:
+          force: true
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+      # ===============================
